<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="author" content="NETOPIA System" />
<meta http-equiv="copyright" content="(c)2007-2009 N E T O P I A System" />
<meta http-equiv="rating" content="general" />
<meta http-equiv="distribution" content="general" />
<link href="http://www.mobilpay.ro/assets/themes/public/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
<link href="http://www.mobilpay.ro/assets/common/img/favicon.ico" rel="shortcut icon" />
<link href="http://www.mobilpay.ro/assets/themes/public/css/print.css" media="print" rel="stylesheet" type="text/css" />
<link href="http://www.mobilpay.ro/assets/themes/public/css/mp.css" media="screen" rel="stylesheet" type="text/css" />
<link href="http://www.mobilpay.ro/assets/themes/public/css/ui.css" media="screen" rel="stylesheet" type="text/css" />
<!--[if IE]> <link href="http://www.mobilpay.ro/assets/themes/public/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" /><![endif]-->
</head>
<body >
<div class="wrapper">
	<div class="page">
		<div class="pagetop clearfix">
			<div class="container clearfix">
					<div class="header">
						<div class="logo">
						  <h1 class="top bottom">
							<a href="/"><span>MobilPay</span></a>
						  </h1>
						</div>
						<div class="menu">
							<a href="#" id="m-1"><span>Cum functioneaza</span></a>
							<a href="#" id="m-2"><span>Cat costa</span></a>
							<a href="#" id="m-3"><span>Demo</span></a>
							<a href="#" id="m-4"><span>Inregistrare</span></a>
							<a href="#" id="m-5"><span>FAQ</span></a>
							<a href="#" id="m-6"><span>Presa</span></a>
							<a href="#" id="m-7"><span>Contact</span></a>
						</div>
					</div>

				<!-- content begin -->
				<div class="span-4">
	<img src="assets/themes/public/img/demo.png"/>
</div>
<?php
require_once 'Mobilpay/Payment/Request/Abstract.php';
require_once 'Mobilpay/Payment/Request/Bitcoin.php';
require_once 'Mobilpay/Payment/Invoice.php';
require_once 'Mobilpay/Payment/Address.php';

//for testing purposes, all payment requests will be sent to the sandbox server. Once your account will be active you must switch back to the live server https://secure.mobilpay.ro/bitcoin
$paymentUrl = 'http://sandboxsecure.mobilpay.ro/bitcoin';

// this is the path on your server to the public certificate. You may download this from Admin -> Conturi de comerciant -> Detalii -> Setari securitate
$x509FilePath 	= '<path_to_public_certificate>';
try
{
	srand((double) microtime() * 1000000);
	$objPmReqCard 						= new Mobilpay_Payment_Request_Bitcoin();
	#merchant account signature - generated by mobilpay.ro for every merchant account
	#semnatura contului de comerciant - mergi pe www.mobilpay.ro Admin -> Conturi de comerciant -> Detalii -> Setari securitate
	$objPmReqCard->signature 			= 'XXXX-XXXX-XXXX-XXXX-XXXX';
	#you should assign here the transaction ID registered by your application for this commercial operation
	#order_id should be unique for a merchant account
	$objPmReqCard->orderId 				= md5(uniqid(rand()));
	#supply return_url and/or confirm_url only if you want to overwrite the ones configured for the service/product when it was created
	#if you don't want to supply a different return/confirm URL, just let it null
	$objPmReqCard->confirmUrl 			= 'http://url-ul-de-confirmare';
	$objPmReqCard->returnUrl 			= 'http://url-ul-de-return';

	#detalii cu privire la plata: moneda, suma, descrierea
	#payment details: currency, amount, description
	$objPmReqCard->invoice = new Mobilpay_Payment_Invoice();
	$objPmReqCard->invoice->currency	= 'RON';
	$objPmReqCard->invoice->amount		= '1.00';
	$objPmReqCard->invoice->details		= 'Plata prin Bitcoin';

	#detalii cu privire la adresa posesorului cardului
	#details on the cardholder address
	$billingAddress 				= new Mobilpay_Payment_Address();
	$billingAddress->type			= $_POST['billing_type'];
	$billingAddress->firstName		= $_POST['billing_first_name'];
	$billingAddress->lastName		= $_POST['billing_last_name'];
	$billingAddress->fiscalNumber	= $_POST['billing_fiscal_number'];
	$billingAddress->identityNumber	= $_POST['billing_identity_number'];
	$billingAddress->country		= $_POST['billing_country'];
	$billingAddress->county			= $_POST['billing_county'];
	$billingAddress->city			= $_POST['billing_city'];
	$billingAddress->zipCode		= $_POST['billing_zip_code'];
	$billingAddress->address		= $_POST['billing_address'];
	$billingAddress->email			= $_POST['billing_email'];
	$billingAddress->mobilePhone	= $_POST['billing_mobile_phone'];
	$billingAddress->bank			= $_POST['billing_bank'];
	$billingAddress->iban			= $_POST['billing_iban'];
	$objPmReqCard->invoice->setBillingAddress($billingAddress);

	#detalii cu privire la adresa de livrare
	#details on the shipping address
	$shippingAddress 				= new Mobilpay_Payment_Address();
	$shippingAddress->type			= $_POST['shipping_type'];
	$shippingAddress->firstName		= $_POST['shipping_first_name'];
	$shippingAddress->lastName		= $_POST['shipping_last_name'];
	$shippingAddress->fiscalNumber	= $_POST['shipping_fiscal_number'];
	$shippingAddress->identityNumber= $_POST['shipping_identity_number'];
	$shippingAddress->country		= $_POST['shipping_country'];
	$shippingAddress->county		= $_POST['shipping_county'];
	$shippingAddress->city			= $_POST['shipping_city'];
	$shippingAddress->zipCode		= $_POST['shipping_zip_code'];
	$shippingAddress->address		= $_POST['shipping_address'];
	$shippingAddress->email			= $_POST['shipping_email'];
	$shippingAddress->mobilePhone	= $_POST['shipping_mobile_phone'];
	$shippingAddress->bank			= $_POST['shipping_bank'];
	$shippingAddress->iban			= $_POST['shipping_iban'];
	$objPmReqCard->invoice->setShippingAddress($shippingAddress);

	$objPmReqCard->encrypt($x509FilePath);
}
catch(Exception $e)
{
}
?>
<div class="span-15 prepend-1">
<h3>Exemplu de implementare plata prin Bitcoin</h3>
<?php if(!isset($e) || !($e instanceof Exception)):?>
<p>
	<form name="frmPaymentRedirect" method="post" action="<?php echo $paymentUrl;?>">
	<input type="hidden" name="env_key" value="<?php echo $objPmReqCard->getEnvKey();?>"/>
	<input type="hidden" name="data" value="<?php echo $objPmReqCard->getEncData();?>"/>
	<p>
		Pentru a finaliza plata vei redirectat catre pagina de plati securizata a mobilpay.ro
	</p>
	<p>
		Daca nu esti redirectat in 5 secunde apasa <input type="image" src="images/12792_mobilpay-96x30.gif" />
	</p>
	</form>
</p>
<script type="text/javascript" language="javascript">
	window.setTimeout(document.frmPaymentRedirect.submit(), 5000);
</script>
<?php else:?>
<p><strong><?php echo $e->getMessage();?></strong></p>
<?php endif;?>
<br/>
<br/>
</body>
</html>
